FROM jenkins/jenkins:lts

USER root

# 1. Install prerequisites and Python
# We include python3-venv because modern Debian blocks global pip installs
RUN apt-get update && \
    apt-get install -y \
    lsb-release \
    python3 \
    python3-pip \
    python3-venv \
    curl \
    gnupg \
    ansible

# 2. Install Docker CLI (Universal Method for Mac/Linux)
# This method works on ARM (Mac) and AMD64 (Intel) automatically
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg

RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

RUN apt-get update && apt-get install -y docker-ce-cli

# 3. Install Kubectl (Universal Method)
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(dpkg --print-architecture)/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Switch back to Jenkins user
USER jenkins