# #ansible/inventory.ini
# [local]
# localhost ansible_connection=local
[localhost]
localhost ansible_connection=local ansible_python_interpreter=/Users/apple/Desktop/Sem7/SPE/trial/et-tu-brute/venv/bin/python